# Generated by Django 3.2.4 on 2021-11-30 04:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataKawasanPrioritas',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nama_kawasan_prioritas', models.TextField(blank=True, null=True)),
                ('perencanaan', models.FloatField(blank=True, null=True)),
                ('kesiapan_kawasan', models.FloatField(blank=True, null=True)),
                ('potensi_konektivitas', models.FloatField(blank=True, null=True)),
                ('dampak_ekonomi', models.FloatField(blank=True, null=True)),
                ('dampak_lingkungan', models.FloatField(blank=True, null=True)),
                ('risiko_bencana', models.FloatField(blank=True, null=True)),
                ('total_nilai', models.FloatField(blank=True, null=True)),
                ('dampak_ekonomi_revisi', models.FloatField(blank=True, null=True)),
                ('kawasan_prioritas', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Data_Kawasan_Prioritas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DeputiId',
            fields=[
                ('deputi_id', models.IntegerField(db_column='Deputi_ID', primary_key=True, serialize=False)),
                ('nama_deputi', models.TextField(db_column='Nama Deputi')),
            ],
            options={
                'db_table': 'Deputi_ID',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DirektoratId',
            fields=[
                ('direktorat_id', models.IntegerField(db_column='Direktorat_ID', primary_key=True, serialize=False)),
                ('nama_direktorat', models.TextField(blank=True, db_column='Nama Direktorat', null=True)),
            ],
            options={
                'db_table': 'Direktorat_ID',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KabupatenId',
            fields=[
                ('provinsi_id', models.IntegerField(db_column='Provinsi_ID')),
                ('kabupaten_id', models.IntegerField(db_column='Kabupaten_ID', primary_key=True, serialize=False)),
                ('nama_kabupaten', models.TextField(db_column='Nama Kabupaten')),
            ],
            options={
                'db_table': 'Kabupaten_ID',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KawasanprioritasId',
            fields=[
                ('kp_id', models.AutoField(db_column='KP_ID', primary_key=True, serialize=False)),
                ('kawasan_prioritas', models.TextField(blank=True, db_column='Kawasan_Prioritas', null=True)),
            ],
            options={
                'db_table': 'KawasanPrioritas_ID',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KlId',
            fields=[
                ('kl_id', models.IntegerField(db_column='KL_ID', primary_key=True, serialize=False)),
                ('nama', models.TextField(db_column='Nama')),
                ('singkatan', models.TextField(blank=True, db_column='Singkatan', null=True)),
            ],
            options={
                'db_table': 'KL_ID',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Longlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul_proyek', models.TextField()),
                ('lokasi_proyek', models.TextField(blank=True, null=True)),
                ('target_2021', models.FloatField(blank=True, null=True)),
                ('target_2022', models.FloatField(blank=True, null=True)),
                ('target_2023', models.FloatField(blank=True, null=True)),
                ('target_2024', models.FloatField(blank=True, null=True)),
                ('target_2025', models.FloatField(blank=True, null=True)),
                ('unit_satuan', models.TextField(blank=True, null=True)),
                ('indikasi_pendanaan_2021', models.FloatField(blank=True, null=True)),
                ('indikasi_pendanaan_2022', models.FloatField(blank=True, null=True)),
                ('indikasi_pendanaan_2023', models.FloatField(blank=True, null=True)),
                ('indikasi_pendanaan_2024', models.FloatField(blank=True, null=True)),
                ('ket_sumber_data', models.TextField(blank=True, db_column='ket_ sumber_data', null=True)),
                ('ket_kl_pelaksana', models.TextField(blank=True, db_column='ket_KL_pelaksana', null=True)),
                ('shortlist_2022', models.BooleanField(blank=True, choices=[(True, 'YES'), (False, 'NO')], null=True)),
                ('shortlist_2023', models.BooleanField(blank=True, choices=[(True, 'YES'), (False, 'NO')], null=True)),
                ('isu_strategis', models.TextField(blank=True, default='', null=True)),
                ('tujuan_lfa', models.TextField(blank=True, db_column='tujuan_LFA', default='', null=True)),
                ('sasaran_lfa', models.TextField(blank=True, db_column='sasaran_LFA', default='', null=True)),
                ('output_lfa', models.TextField(blank=True, db_column='output_LFA', default='', null=True)),
                ('sumber_bahasan', models.TextField(blank=True, null=True)),
                ('prioritas_tahun_2022', models.TextField(blank=True, null=True)),
                ('prioritas_tahun_2023', models.TextField(blank=True, null=True)),
                ('prioritas_tahun_2024', models.TextField(blank=True, null=True)),
                ('sub_tema_rkp', models.TextField(blank=True, null=True)),
                ('klasifikasi_proyek', models.TextField(blank=True, null=True)),
                ('jenis_impact', models.TextField(blank=True, null=True)),
                ('staging_perkembangan', models.TextField(blank=True, null=True)),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('usulan_baru', models.BooleanField(blank=True, choices=[(True, 'YES'), (False, 'NO')], default=False, null=True)),
                ('shortlist', models.BooleanField(blank=True, choices=[(True, 'YES'), (False, 'NO')], default=False, null=True)),
                ('prarakorgub', models.BooleanField(blank=True, choices=[(True, 'YES'), (False, 'NO')], default=False, null=True)),
                ('rakorgub', models.BooleanField(blank=True, choices=[(True, 'YES'), (False, 'NO')], default=False, null=True)),
                ('rakortekbang', models.BooleanField(blank=True, choices=[(True, 'YES'), (False, 'NO')], default=False, null=True)),
                ('musrenbangprov', models.BooleanField(blank=True, choices=[(True, 'YES'), (False, 'NO')], default=False, null=True)),
                ('musrenbangnas', models.BooleanField(blank=True, choices=[(True, 'YES'), (False, 'NO')], default=False, null=True)),
                ('endorsement', models.BooleanField(blank=True, choices=[(True, 'YES'), (False, 'NO')], default=False, null=True)),
            ],
            options={
                'db_table': 'Longlist',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MajorprojectId',
            fields=[
                ('mp_id', models.IntegerField(db_column='MP_ID', primary_key=True, serialize=False)),
                ('nama_major_project', models.TextField(blank=True, db_column='Nama Major Project', null=True)),
            ],
            options={
                'db_table': 'MajorProject_ID',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MitraId',
            fields=[
                ('mitra_id', models.IntegerField(db_column='Mitra_ID', primary_key=True, serialize=False)),
                ('nama_direktorat_mitra', models.TextField(db_column='Nama Direktorat Mitra')),
                ('deputi', models.IntegerField(blank=True, db_column='Deputi', null=True)),
            ],
            options={
                'db_table': 'Mitra_ID',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProvinsiId',
            fields=[
                ('provinsi_id', models.IntegerField(db_column='Provinsi_ID', primary_key=True, serialize=False)),
                ('nama_provinsi', models.TextField(blank=True, db_column='Nama Provinsi', null=True)),
            ],
            options={
                'db_table': 'Provinsi_ID',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProyekId',
            fields=[
                ('nama_proyek', models.TextField(db_column='Nama Proyek')),
                ('proyek_idd', models.IntegerField(db_column='Proyek_IDD', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Proyek_ID',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StatusId',
            fields=[
                ('status_id', models.IntegerField(db_column='Status_ID', primary_key=True, serialize=False)),
                ('nama_status', models.TextField(blank=True, db_column='Nama Status', null=True)),
            ],
            options={
                'db_table': 'Status_ID',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SubditId',
            fields=[
                ('subdit_id', models.IntegerField(db_column='Subdit_ID', primary_key=True, serialize=False)),
                ('nama_subdit', models.TextField(blank=True, db_column='Nama Subdit', null=True)),
            ],
            options={
                'db_table': 'Subdit_ID',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SubtemaId',
            fields=[
                ('sub_tema_id', models.IntegerField(db_column='Sub_Tema_ID', primary_key=True, serialize=False)),
                ('subtema_rkp_2022', models.TextField(blank=True, db_column='Subtema RKP 2022', null=True)),
            ],
            options={
                'db_table': 'SubTema_ID',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SumberdataId',
            fields=[
                ('sumberdata_id', models.IntegerField(db_column='SumberData_ID', primary_key=True, serialize=False)),
                ('nama_sumber', models.TextField(blank=True, db_column='Nama Sumber', null=True)),
            ],
            options={
                'db_table': 'SumberData_ID',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TahapanId',
            fields=[
                ('tahapan_id', models.IntegerField(db_column='Tahapan_ID', primary_key=True, serialize=False)),
                ('nama_tahapan', models.TextField(blank=True, db_column='Nama Tahapan', null=True)),
            ],
            options={
                'db_table': 'Tahapan_ID',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserStatus',
            fields=[
                ('user_status', models.IntegerField(db_column='User_Status', primary_key=True, serialize=False)),
                ('nama_status', models.TextField(blank=True, db_column='Nama Status', null=True)),
            ],
            options={
                'db_table': 'User_Status',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CsvLongList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.FileField(upload_to='csv_longlist', validators=[django.core.validators.FileExtensionValidator(['csv'])])),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SkoringProyek',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nilai_raw_korelasi_sasaran', models.FloatField(blank=True, default=0, null=True)),
                ('nilai_raw_korelasi_output', models.FloatField(blank=True, default=0, null=True)),
                ('nilai_raw_MP', models.FloatField(blank=True, default=0, null=True)),
                ('nilai_raw_investasi', models.FloatField(blank=True, default=0, null=True)),
                ('proyek', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dashboard.longlist')),
            ],
        ),
        migrations.CreateModel(
            name='IsuStrategis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_isu', models.CharField(blank=True, max_length=400, null=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='dashboard.isustrategis')),
                ('provinsi', models.ForeignKey(blank=True, db_column='provinsi', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.provinsiid')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HasilSkoringProyek',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nilai_raw_korelasi_sasaran', models.FloatField(blank=True, default=0, null=True)),
                ('nilai_raw_korelasi_output', models.FloatField(blank=True, default=0, null=True)),
                ('nilai_raw_MP', models.FloatField(blank=True, default=0, null=True)),
                ('nilai_raw_investasi', models.FloatField(blank=True, default=0, null=True)),
                ('proyek', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dashboard.longlist')),
            ],
        ),
        migrations.CreateModel(
            name='AnalisisKerangkaLogis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_hirarki_logis', models.CharField(max_length=250, unique=True)),
                ('indikator', models.CharField(blank=True, max_length=400, null=True)),
                ('sumber_data', models.CharField(blank=True, max_length=400, null=True)),
                ('sumber', models.CharField(blank=True, max_length=400, null=True)),
                ('asumsi', models.CharField(blank=True, max_length=400, null=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='dashboard.analisiskerangkalogis')),
                ('provinsi', models.ForeignKey(blank=True, db_column='provinsi', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.provinsiid')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
