# Generated by Django 3.2.4 on 2021-06-18 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provinsi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_provinsi', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Proyek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_proyek', models.CharField(max_length=1000)),
                ('tahun_proyek', models.IntegerField(max_length=4)),
                ('id_proyek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.provinsi')),
            ],
        ),
    ]
