# Generated by Django 3.2.4 on 2021-06-18 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proyek',
            old_name='id_proyek',
            new_name='provinsi',
        ),
        migrations.AlterField(
            model_name='proyek',
            name='tahun_proyek',
            field=models.IntegerField(),
        ),
    ]
