# Generated by Django 3.2.4 on 2021-12-13 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_skoringproyek_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutputLFA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_output', models.TextField()),
                ('indikator', models.TextField(max_length=500)),
                ('sumber_data', models.TextField(max_length=500)),
                ('asumsi', models.TextField(max_length=500)),
                ('nilai', models.FloatField(default=0)),
                ('pengaruh_output_sasaran', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SasaranLFA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_sasaran', models.TextField()),
                ('indikator', models.TextField(max_length=500)),
                ('sumber_data', models.TextField(max_length=500)),
                ('asumsi', models.TextField(max_length=500)),
                ('nilai', models.FloatField(default=0)),
                ('pengaruh_sasaran_tujuan', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TujuanLFA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_tujuan', models.TextField()),
                ('tahun', models.IntegerField(blank=True, null=True)),
                ('indikator', models.TextField(max_length=500)),
                ('sumber_data', models.TextField(max_length=500)),
                ('asumsi', models.TextField(max_length=500)),
                ('nilai', models.FloatField(default=0)),
                ('provinsi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.provinsiid')),
            ],
        ),
        migrations.AddField(
            model_name='isustrategis',
            name='tahun',
            field=models.IntegerField(choices=[(2019, 2019), (2020, 2020), (2021, 2021)], default=2019),
        ),
        migrations.DeleteModel(
            name='AnalisisKerangkaLogis',
        ),
        migrations.AddField(
            model_name='sasaranlfa',
            name='tujuan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.tujuanlfa'),
        ),
        migrations.AddField(
            model_name='outputlfa',
            name='sasaran',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.sasaranlfa'),
        ),
    ]
