# Generated by Django 3.2.4 on 2021-06-24 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_choice_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Endorsement',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('urutan', models.IntegerField()),
                ('nama_kegiatan', models.TextField()),
                ('satuan', models.TextField(blank=True, null=True)),
                ('pn_id', models.IntegerField()),
                ('major_project', models.TextField(blank=True, null=True)),
                ('lokasi', models.TextField(blank=True, null=True)),
                ('kl_id', models.IntegerField()),
                ('direktorat_mitra', models.TextField(blank=True, null=True)),
                ('rakorgub', models.BooleanField(blank=True, null=True)),
                ('rakortek', models.BooleanField(blank=True, null=True)),
                ('musrenbangnas', models.BooleanField(blank=True, null=True)),
                ('rakortekbang', models.BooleanField(blank=True, null=True)),
                ('status_approval', models.TextField(blank=True, null=True)),
                ('ket_approval', models.TextField(blank=True, null=True)),
                ('vol', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'endorsement',
                'managed': False,
            },
        ),
    ]
