# Generated by Django 3.2.4 on 2021-06-28 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_endorsement'),
    ]

    operations = [
        migrations.CreateModel(
            name='KementrianLembaga',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nama_kementrian_lembaga', models.TextField(blank=True, db_column='Nama Kementrian Lembaga', null=True)),
            ],
            options={
                'db_table': 'kementrian_lembaga',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KeteranganPrioritasNasional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keterangan_prioritas_nasional', models.TextField(blank=True, db_column='keterangan prioritas nasional', null=True)),
            ],
            options={
                'db_table': 'keterangan_prioritas_nasional',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ListProvinsi',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('prov_id', models.IntegerField(blank=True, null=True)),
                ('nama_provinsi', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'list_provinsi',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='proyek',
            name='provinsi',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Provinsi',
        ),
        migrations.DeleteModel(
            name='Proyek',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
