# Generated by Django 3.2.4 on 2021-07-27 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20210628_1523'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeputiId',
            fields=[
                ('deputi_id', models.IntegerField(db_column='Deputi_ID', primary_key=True, serialize=False)),
                ('nama_deputi', models.TextField(db_column='Nama Deputi')),
            ],
            options={
                'db_table': 'Deputi_ID',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DirektoratId',
            fields=[
                ('direktorat_id', models.IntegerField(db_column='Direktorat_ID', primary_key=True, serialize=False)),
                ('nama_direktorat', models.TextField(blank=True, db_column='Nama Direktorat', null=True)),
            ],
            options={
                'db_table': 'Direktorat_ID',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KabupatenId',
            fields=[
                ('provinsi_id', models.IntegerField(db_column='Provinsi_ID')),
                ('kabupaten_id', models.IntegerField(db_column='Kabupaten_ID', primary_key=True, serialize=False)),
                ('nama_kabupaten', models.TextField(db_column='Nama Kabupaten')),
            ],
            options={
                'db_table': 'Kabupaten_ID',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KlId',
            fields=[
                ('kl_id', models.IntegerField(db_column='KL_ID', primary_key=True, serialize=False)),
                ('nama', models.TextField(db_column='Nama')),
                ('singkatan', models.TextField(blank=True, db_column='Singkatan', null=True)),
            ],
            options={
                'db_table': 'KL_ID',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Longlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ro_id', models.IntegerField(blank=True, null=True)),
                ('judul_proyek', models.TextField()),
                ('lokasi_proyek', models.TextField(blank=True, null=True)),
                ('target_2021', models.IntegerField(blank=True, null=True)),
                ('target_2022', models.IntegerField(blank=True, null=True)),
                ('target_2023', models.IntegerField(blank=True, null=True)),
                ('target_2024', models.IntegerField(blank=True, null=True)),
                ('target_2025', models.IntegerField(blank=True, null=True)),
                ('indikasi_pendanaan_2021', models.FloatField(blank=True, null=True)),
                ('indikasi_pendanaan_2022', models.FloatField(blank=True, null=True)),
                ('indikasi_pendanaan_2023', models.FloatField(blank=True, null=True)),
                ('indikasi_pendanaan_2024', models.FloatField(blank=True, null=True)),
                ('isu_strategis', models.TextField(blank=True, null=True)),
                ('tujuan_lfa', models.TextField(blank=True, db_column='tujuan_LFA', null=True)),
                ('sasaran_lfa', models.TextField(blank=True, db_column='sasaran_LFA', null=True)),
                ('output_lfa', models.TextField(blank=True, db_column='output_LFA', null=True)),
                ('sumber_bahasan', models.TextField(blank=True, null=True)),
                ('taging_kawasan_prioritas', models.TextField(blank=True, null=True)),
                ('jenis_proyek', models.TextField(blank=True, null=True)),
                ('klasifikasi_proyek', models.TextField(blank=True, null=True)),
                ('jenis_impact', models.TextField(blank=True, null=True)),
                ('staging_perkembangan', models.TextField(blank=True, null=True)),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('usulan_baru', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Longlist',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MajorprojectId',
            fields=[
                ('mp_id', models.IntegerField(db_column='MP_ID', primary_key=True, serialize=False)),
                ('nama_major_project', models.TextField(blank=True, db_column='Nama Major Project', null=True)),
            ],
            options={
                'db_table': 'MajorProject_ID',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MitraId',
            fields=[
                ('mitra_id', models.IntegerField(db_column='Mitra_ID', primary_key=True, serialize=False)),
                ('nama_direktorat_mitra', models.TextField(db_column='Nama Direktorat Mitra')),
                ('deputi', models.IntegerField(blank=True, db_column='Deputi', null=True)),
            ],
            options={
                'db_table': 'Mitra_ID',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProvinsiId',
            fields=[
                ('provinsi_id', models.IntegerField(db_column='Provinsi_ID', primary_key=True, serialize=False)),
                ('nama_provinsi', models.TextField(blank=True, db_column='Nama Provinsi', null=True)),
            ],
            options={
                'db_table': 'Provinsi_ID',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProyekId',
            fields=[
                ('nama_proyek', models.TextField(db_column='Nama Proyek')),
                ('proyek_idd', models.IntegerField(db_column='Proyek_IDD', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Proyek_ID',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StatusId',
            fields=[
                ('status_id', models.IntegerField(db_column='Status_ID', primary_key=True, serialize=False)),
                ('nama_status', models.TextField(blank=True, db_column='Nama Status', null=True)),
            ],
            options={
                'db_table': 'Status_ID',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SubditId',
            fields=[
                ('subdit_id', models.IntegerField(db_column='Subdit_ID', primary_key=True, serialize=False)),
                ('nama_subdit', models.TextField(blank=True, db_column='Nama Subdit', null=True)),
            ],
            options={
                'db_table': 'Subdit_ID',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SubtemaId',
            fields=[
                ('sub_tema_id', models.IntegerField(db_column='Sub_Tema_ID', primary_key=True, serialize=False)),
                ('subtema_rkp_2022', models.TextField(blank=True, db_column='Subtema RKP 2022', null=True)),
            ],
            options={
                'db_table': 'SubTema_ID',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SumberdataId',
            fields=[
                ('sumberdata_id', models.IntegerField(db_column='SumberData_ID', primary_key=True, serialize=False)),
                ('nama_sumber', models.TextField(blank=True, db_column='Nama Sumber', null=True)),
            ],
            options={
                'db_table': 'SumberData_ID',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TahapanId',
            fields=[
                ('tahapan_id', models.IntegerField(db_column='Tahapan_ID', primary_key=True, serialize=False)),
                ('nama_tahapan', models.TextField(blank=True, db_column='Nama Tahapan', null=True)),
            ],
            options={
                'db_table': 'Tahapan_ID',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserStatus',
            fields=[
                ('user_status', models.IntegerField(db_column='User_Status', primary_key=True, serialize=False)),
                ('nama_status', models.TextField(blank=True, db_column='Nama Status', null=True)),
            ],
            options={
                'db_table': 'User_Status',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ShortList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tahun_shortlist_2023', models.IntegerField(null=True)),
                ('judul_proyek', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dashboard.longlist')),
            ],
        ),
    ]
