# Generated by Django 3.2.4 on 2021-12-13 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_tujuanlfa_tahun'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outputlfa',
            name='asumsi',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='outputlfa',
            name='indikator',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='outputlfa',
            name='sumber_data',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='sasaranlfa',
            name='asumsi',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='sasaranlfa',
            name='indikator',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='sasaranlfa',
            name='sumber_data',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='tujuanlfa',
            name='asumsi',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='tujuanlfa',
            name='indikator',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='tujuanlfa',
            name='sumber_data',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
