# Generated by Django 3.2.4 on 2021-12-15 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20211213_0758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tujuanlfa',
            name='nama_tujuan',
            field=models.TextField(blank=True, null=True),
        ),
    ]
