# Generated by Django 3.2.4 on 2021-08-05 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_csvlonglist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='csvlonglist',
            name='user_uploaded',
        ),
    ]
