# Generated by Django 3.2.4 on 2021-08-18 04:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_remove_csvlonglist_user_uploaded'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Endorsement',
        ),
        migrations.DeleteModel(
            name='KementrianLembaga',
        ),
        migrations.DeleteModel(
            name='KeteranganPrioritasNasional',
        ),
        migrations.DeleteModel(
            name='ListProvinsi',
        ),
        migrations.AlterField(
            model_name='csvlonglist',
            name='file_name',
            field=models.FileField(upload_to='csv_longlist', validators=[django.core.validators.FileExtensionValidator(['csv'])]),
        ),
    ]
