# Generated by Django 3.2.4 on 2021-09-29 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_delete_shortlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='KawasanprioritasId',
            fields=[
                ('kp_id', models.AutoField(db_column='KP_ID', primary_key=True, serialize=False)),
                ('kawasan_prioritas', models.TextField(blank=True, db_column='Kawasan_Prioritas', null=True)),
            ],
            options={
                'db_table': 'KawasanPrioritas_ID',
                'managed': False,
            },
        ),
    ]
