# Generated by Django 3.2.4 on 2021-12-21 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20211220_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='isustrategis',
            name='provinsi',
            field=models.ForeignKey(blank=True, db_column='provinsi', null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.provinsiid'),
        ),
        migrations.AlterField(
            model_name='outputlfa',
            name='sasaran',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.sasaranlfa'),
        ),
        migrations.AlterField(
            model_name='sasaranlfa',
            name='tujuan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.tujuanlfa'),
        ),
        migrations.AlterField(
            model_name='tujuanlfa',
            name='provinsi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.provinsiid'),
        ),
    ]
