# Generated by Django 3.2.4 on 2021-10-26 01:09

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_kawasanprioritasid'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataKawasanPrioritas',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nama_kawasan_prioritas', models.TextField(blank=True, null=True)),
                ('perencanaan', models.FloatField(blank=True, null=True)),
                ('kesiapan_kawasan', models.FloatField(blank=True, null=True)),
                ('potensi_konektivitas', models.FloatField(blank=True, null=True)),
                ('dampak_ekonomi', models.FloatField(blank=True, null=True)),
                ('dampak_lingkungan', models.FloatField(blank=True, null=True)),
                ('risiko_bencana', models.FloatField(blank=True, null=True)),
                ('total_nilai', models.FloatField(blank=True, null=True)),
                ('dampak_ekonomi_revisi', models.FloatField(blank=True, null=True)),
                ('kawasan_prioritas', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Data_Kawasan_Prioritas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='dashboard.genre')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
