# Generated by Django 3.2.4 on 2022-04-07 07:20

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_auto_20220126_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='outputlfa',
            name='creation_time',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='isustrategis',
            name='nama_isu',
            field=models.CharField(blank=True, default='', max_length=400, null=True),
        ),
        migrations.CreateModel(
            name='NewIsuStrategis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_isu', models.CharField(blank=True, default='', max_length=400, null=True)),
                ('tahun', models.IntegerField(choices=[(2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025), (2026, 2026)], default=2019)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='dashboard.newisustrategis')),
                ('provinsi', models.ForeignKey(blank=True, db_column='provinsi', null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.provinsiid')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
