# Generated by Django 3.2.4 on 2021-10-26 03:35

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_datakawasanprioritas_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalisisKerangkaLogis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_hirarki_logis', models.CharField(max_length=250, unique=True)),
                ('indikator', models.CharField(blank=True, max_length=400, null=True)),
                ('sumber_data', models.CharField(blank=True, max_length=400, null=True)),
                ('sumber', models.CharField(blank=True, max_length=400, null=True)),
                ('asumsi', models.CharField(blank=True, max_length=400, null=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('provinsi', models.ForeignKey(blank=True, db_column='provinsi', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.provinsiid')),
                ('sasaran', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='output_name', to='dashboard.analisiskerangkalogis')),
                ('tujuan', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sasaran_name', to='dashboard.analisiskerangkalogis')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
