# Generated by Django 3.2.4 on 2022-05-30 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_auto_20220407_1420'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitsatuanID',
            fields=[
                ('unitsatuan_id', models.IntegerField(db_column='Unitsatuan_ID', primary_key=True, serialize=False)),
                ('nama_satuan', models.TextField(blank=True, db_column='Nama_Satuan', null=True)),
            ],
            options={
                'db_table': 'Unitsatuan_ID',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='outputlfa',
            name='nilai',
        ),
        migrations.RemoveField(
            model_name='sasaranlfa',
            name='nilai',
        ),
        migrations.RemoveField(
            model_name='tujuanlfa',
            name='nilai',
        ),
        migrations.AddField(
            model_name='newisustrategis',
            name='data_pendukung',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='outputlfa',
            name='baseline',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='outputlfa',
            name='tahun_anggaran',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='outputlfa',
            name='target',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='outputlfa',
            name='unit_satuan_baseline',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='outputlfa',
            name='unit_satuan_target',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='sasaranlfa',
            name='baseline',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='sasaranlfa',
            name='tahun_anggaran',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='sasaranlfa',
            name='target',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='sasaranlfa',
            name='unit_satuan_baseline',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='sasaranlfa',
            name='unit_satuan_target',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='tujuanlfa',
            name='baseline',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='tujuanlfa',
            name='tahun_anggaran',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='tujuanlfa',
            name='target',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='tujuanlfa',
            name='unit_satuan_baseline',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='tujuanlfa',
            name='unit_satuan_target',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='newisustrategis',
            name='nama_isu',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='newisustrategis',
            name='provinsi',
            field=models.ForeignKey(db_column='provinsi', null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.provinsiid'),
        ),
        migrations.AlterField(
            model_name='outputlfa',
            name='sasaran',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='dashboard.sasaranlfa'),
        ),
        migrations.AlterField(
            model_name='sasaranlfa',
            name='tujuan',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='dashboard.tujuanlfa'),
        ),
        migrations.AlterField(
            model_name='tujuanlfa',
            name='nama_tujuan',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='tujuanlfa',
            name='provinsi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.provinsiid'),
        ),
        migrations.AddField(
            model_name='outputlfa',
            name='unitsatuanbaseline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unitsatuan_baseline_output', to='dashboard.unitsatuanid'),
        ),
        migrations.AddField(
            model_name='outputlfa',
            name='unitsatuantarget',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unitsatuan_target_output', to='dashboard.unitsatuanid'),
        ),
        migrations.AddField(
            model_name='sasaranlfa',
            name='unitsatuanbaseline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unitsatuan_baseline_sasaran', to='dashboard.unitsatuanid'),
        ),
        migrations.AddField(
            model_name='sasaranlfa',
            name='unitsatuantarget',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unitsatuan_target_sasaran', to='dashboard.unitsatuanid'),
        ),
        migrations.AddField(
            model_name='tujuanlfa',
            name='unitsatuanbaseline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unitsatuan_baseline_tujuan', to='dashboard.unitsatuanid'),
        ),
        migrations.AddField(
            model_name='tujuanlfa',
            name='unitsatuantarget',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unitsatuan_target_tujuan', to='dashboard.unitsatuanid'),
        ),
    ]
