# Generated by Django 3.2.4 on 2021-10-27 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_auto_20211026_1047'),
    ]

    operations = [
        migrations.CreateModel(
            name='IsuStrategis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_isu', models.CharField(blank=True, max_length=400, null=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('provinsi', models.ForeignKey(blank=True, db_column='provinsi', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.provinsiid')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
