# Generated by Django 3.2.4 on 2021-10-27 05:47

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_isustrategis'),
    ]

    operations = [
        migrations.AddField(
            model_name='isustrategis',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='dashboard.isustrategis'),
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
