# Generated by Django 3.2.4 on 2021-11-26 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_auto_20211027_1247'),
    ]

    operations = [
        migrations.CreateModel(
            name='HasilSkoringProyek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nilai_raw_korelasi_sasaran', models.FloatField(blank=True, null=True)),
                ('nilai_raw_korelasi_output', models.FloatField(blank=True, null=True)),
                ('nilai_raw_MP', models.FloatField(blank=True, null=True)),
                ('nilai_raw_investasi', models.FloatField(blank=True, null=True)),
                ('proyek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.longlist')),
            ],
        ),
    ]
