# Generated by Django 3.2.4 on 2021-11-26 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_hasilskoringproyek'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hasilskoringproyek',
            name='proyek',
        ),
    ]
