# Generated by Django 3.2.4 on 2021-11-26 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_remove_hasilskoringproyek_proyek'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=250)),
            ],
        ),
    ]
