# Generated by Django 3.2.4 on 2021-11-26 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_testname'),
    ]

    operations = [
        migrations.AddField(
            model_name='hasilskoringproyek',
            name='proyek',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.longlist'),
        ),
    ]
