# Generated by Django 3.2.4 on 2021-11-29 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_hasilskoringproyek_proyek'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hasilskoringproyek',
            name='proyek',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.longlist'),
        ),
    ]
