# Generated by Django 3.2.14 on 2022-09-29 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Nama Dokumen')),
                ('description', models.CharField(default='', max_length=50, verbose_name='Deskripsi Isi Dokumen')),
                ('file', models.FileField(upload_to='', verbose_name='Unggah File')),
                ('extension_type', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'XLSX'), ('csv', 'CSV'), ('doc', 'DOCX')], max_length=7)),
                ('document_type', models.CharField(choices=[('usulan', 'Usulan'), ('audiensi', 'Audiensi')], max_length=13)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UsulanKlinik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('provinsi', models.CharField(choices=[('aceh', 'Aceh'), ('riau', 'Riau'), ('bengkulu', 'Bengkulu'), ('jawa Timur', 'Jawa Timur'), ('jambi', 'Jambi'), ('lampung', 'Lampung'), ('sumatera-selatan', 'Sumatera Selatan'), ('sumatera-barat', 'Sumatera Barat'), ('sumatera-utara', 'Sumatera Utara'), ('dki-jakarta', 'DKI Jakarta'), ('jawa-tengah', 'Jawa Tengah'), ('kepulauan-riau', 'Kepulauan Riau'), ('banten', 'Banten'), ('di-yogyakarta', 'DI Yogyakarta'), ('bangka-belitung', 'Bangka Belitung'), ('jawa-barat', 'Jawa Barat'), ('bali', 'Bali')], max_length=20)),
                ('kabkota', models.CharField(max_length=20)),
                ('nomor_usulan', models.CharField(max_length=30)),
                ('tanggal_usulan', models.DateTimeField()),
                ('target', models.CharField(max_length=7)),
                ('kebutuhan_anggaran', models.FloatField()),
                ('lokasi', models.CharField(max_length=15)),
                ('indikasi_tahun', models.CharField(max_length=5)),
                ('kewenangan', models.CharField(choices=[('pusat', 'Pusat'), ('daerah', 'Daerah'), ('provinsi', 'Provinsi'), ('kabupaten', 'Kabupaten'), ('no-status', 'No Status')], max_length=15)),
                ('k_l_d', models.CharField(max_length=25)),
                ('sektor', models.CharField(max_length=20)),
                ('jenis_usulan', models.CharField(max_length=14)),
                ('forum_perencanaan', models.CharField(max_length=8)),
                ('dasar_usulan', models.CharField(max_length=10)),
                ('kesepakatan', models.CharField(choices=[('approve', 'Diterima'), ('disallow', 'Ditolak'), ('further-discuss', 'Dibahas Lebih Lanjut'), ('no-status', 'Tanpa Status')], max_length=15)),
                ('keterangan', models.TextField()),
                ('sumber_pendanaan', models.CharField(max_length=9)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UsulanLanjut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('provinsi', models.CharField(choices=[('aceh', 'Aceh'), ('riau', 'Riau'), ('bengkulu', 'Bengkulu'), ('jawa Timur', 'Jawa Timur'), ('jambi', 'Jambi'), ('lampung', 'Lampung'), ('sumatera-selatan', 'Sumatera Selatan'), ('sumatera-barat', 'Sumatera Barat'), ('sumatera-utara', 'Sumatera Utara'), ('dki-jakarta', 'DKI Jakarta'), ('jawa-tengah', 'Jawa Tengah'), ('kepulauan-riau', 'Kepulauan Riau'), ('banten', 'Banten'), ('di-yogyakarta', 'DI Yogyakarta'), ('bangka-belitung', 'Bangka Belitung'), ('jawa-barat', 'Jawa Barat'), ('bali', 'Bali')], max_length=20)),
                ('kabkota', models.CharField(max_length=20)),
                ('nomor_usulan', models.CharField(max_length=30)),
                ('tanggal_usulan', models.DateTimeField()),
                ('uraian_usulan', models.CharField(max_length=10)),
                ('mekanisme_usulan', models.CharField(max_length=9)),
                ('rekomendasi', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UsulanPemda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('provinsi', models.CharField(choices=[('aceh', 'Aceh'), ('riau', 'Riau'), ('bengkulu', 'Bengkulu'), ('jawa Timur', 'Jawa Timur'), ('jambi', 'Jambi'), ('lampung', 'Lampung'), ('sumatera-selatan', 'Sumatera Selatan'), ('sumatera-barat', 'Sumatera Barat'), ('sumatera-utara', 'Sumatera Utara'), ('dki-jakarta', 'DKI Jakarta'), ('jawa-tengah', 'Jawa Tengah'), ('kepulauan-riau', 'Kepulauan Riau'), ('banten', 'Banten'), ('di-yogyakarta', 'DI Yogyakarta'), ('bangka-belitung', 'Bangka Belitung'), ('jawa-barat', 'Jawa Barat'), ('bali', 'Bali')], max_length=20)),
                ('kabkota', models.CharField(max_length=20)),
                ('nomor_usulan', models.CharField(max_length=30)),
                ('tanggal_usulan', models.DateTimeField()),
                ('judul_surat', models.CharField(max_length=50)),
                ('jenis_surat', models.CharField(max_length=14)),
                ('daftar_usulan_proyek', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FileHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('update_status', models.CharField(choices=[('create', 'CREATE'), ('edit', 'EDIT'), ('delete', 'DELETE')], max_length=7)),
                ('description', models.CharField(max_length=30, verbose_name='Deskripsi Perubahan')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('file', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='app_srupdt.file')),
                ('parent', mptt.fields.TreeForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='LastModified', to='app_srupdt.filehistory')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
