# Generated by Django 3.2.14 on 2022-10-04 03:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_srupdt', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filehistory',
            name='update_status',
        ),
        migrations.AddField(
            model_name='filehistory',
            name='latest_status',
            field=models.CharField(choices=[('create', 'CREATE'), ('edit', 'EDIT'), ('delete', 'DELETE'), ('view', 'VIEW')], default='no-status', max_length=19),
        ),
        migrations.AlterField(
            model_name='file',
            name='extension_type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('excel', 'XLSX'), ('csv', 'CSV'), ('doc', 'DOCX')], editable=False, max_length=7),
        ),
        migrations.AlterField(
            model_name='file',
            name='name',
            field=models.CharField(editable=False, max_length=60, unique=True, verbose_name='Nama Dokumen'),
        ),
        migrations.AlterField(
            model_name='file',
            name='uploaded_by',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='filehistory',
            name='description',
            field=models.CharField(choices=[('FC1', 'Ubah Nama'), ('FC2', 'Salah File'), ('FC3', 'Ukuran File Besar')], max_length=30, verbose_name='Deskripsi Perubahan'),
        ),
    ]
