# Generated by Django 3.2.14 on 2022-11-07 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_srupdt', '0004_auto_20221105_2016'),
    ]

    operations = [
    ]
