# Generated by Django 3.2.14 on 2022-11-07 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_srupdt', '0005_auto_20221107_1240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiensi',
            name='forum_perencanaan_diusulkan',
        ),
        migrations.RemoveField(
            model_name='audiensi',
            name='status_kesiapan_lahan',
        ),
        migrations.RemoveField(
            model_name='audiensi',
            name='status_studi_persiapan',
        ),
        migrations.RemoveField(
            model_name='klinikkonsultasi',
            name='catatan_pembahasan',
        ),
        migrations.RemoveField(
            model_name='klinikkonsultasi',
            name='penelaahan_akhir',
        ),
        migrations.RemoveField(
            model_name='penelaahanawal',
            name='rekomendasi_penelaahan_awal',
        ),
        migrations.AddField(
            model_name='audiensi',
            name='catatan_readiness_criteria',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='audiensi',
            name='forum_perencanaan_pernah_diusulkan',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='audiensi',
            name='rc_ded',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='audiensi',
            name='rc_fs',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='audiensi',
            name='rc_lahan',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='audiensi',
            name='rc_pra_fs',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='klinikkonsultasi',
            name='catatan_penelaahan_akhir',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='klinikkonsultasi',
            name='hasil_penelaahan_akhir',
            field=models.CharField(blank=True, choices=[('tidak direkomendasikan', 'Tidak Direkomendasikan'), ('direkomendasikan', 'Direkomendasikan')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='penelaahanawal',
            name='hasil_penelaahan_awal',
            field=models.CharField(blank=True, choices=[('tidak direkomendasikan', 'Tidak Direkomendasikan'), ('dibahas lebih lanjut', 'Dibahas Lebih Lanjut')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='audiensi',
            name='catatan_audiensi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='audiensi',
            name='dasar_usulan',
            field=models.CharField(blank=True, choices=[('audiensi', 'Audiensi'), ('surat', 'Surat')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='audiensi',
            name='indikasi_tahun_pembangunan',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='audiensi',
            name='jenis_usulan',
            field=models.CharField(blank=True, choices=[('infrastruktur', 'Infrastruktur'), ('non infrastruktur', 'Non infrastruktur')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='audiensi',
            name='kebutuhan_anggaran',
            field=models.IntegerField(blank=True, null=True, verbose_name='Kebutuhan anggaran (dalam juta rupiah)'),
        ),
        migrations.AlterField(
            model_name='audiensi',
            name='kementerian_lembaga_daerah',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='audiensi',
            name='keterangan_tambahan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='audiensi',
            name='kewenangan',
            field=models.CharField(blank=True, choices=[('pusat', 'Pusat'), ('daerah', 'Daerah')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='audiensi',
            name='kriteria_usulan',
            field=models.CharField(blank=True, choices=[('usulan baru', 'Usulan Baru'), ('usulan lama', 'Usulan Lama')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='audiensi',
            name='lokasi_spesifik',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='audiensi',
            name='nomenklatur_usulan',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='audiensi',
            name='sektor_bappenas',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='audiensi',
            name='target_usulan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='klinikkonsultasi',
            name='indikasi_sumber_pendanaan',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='klinikkonsultasi',
            name='nodin_laporan',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='klinikkonsultasi',
            name='surat_jawaban',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='penelaahanawal',
            name='ketersediaan_proyek_usulan',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='penelaahanawal',
            name='memenuhi_kelengkapan_minimum_rediness_criteria',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='penelaahanawal',
            name='terdapat_identifikasi_kewenangan_pusatdaerah_dari_usulan_proyek',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='penelaahanawal',
            name='terdapat_justifikasi_kebutuhan_usulan_proyek',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='penelaahanawal',
            name='terdapat_nomenklatur_usulan_yang_jelas',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='surat',
            name='jenis_surat',
            field=models.CharField(blank=True, choices=[('usulan', 'Penyampaian Usulan'), ('audiensi', 'Permohonan Audiensi')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='surat',
            name='judul_surat',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='surat',
            name='kabupaten_kota',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='surat',
            name='nomor_surat',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='surat',
            name='provinsi',
            field=models.CharField(blank=True, choices=[('aceh', 'Aceh'), ('riau', 'Riau'), ('bengkulu', 'Bengkulu'), ('jawa Timur', 'Jawa Timur'), ('jambi', 'Jambi'), ('lampung', 'Lampung'), ('sumatera-selatan', 'Sumatera Selatan'), ('sumatera-barat', 'Sumatera Barat'), ('sumatera-utara', 'Sumatera Utara'), ('dki-jakarta', 'DKI Jakarta'), ('jawa-tengah', 'Jawa Tengah'), ('kepulauan-riau', 'Kepulauan Riau'), ('banten', 'Banten'), ('di-yogyakarta', 'DI Yogyakarta'), ('bangka-belitung', 'Bangka Belitung'), ('jawa-barat', 'Jawa Barat'), ('bali', 'Bali')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='surat',
            name='tanggal_surat',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
