# Generated by Django 3.2.14 on 2022-11-07 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_srupdt', '0006_auto_20221107_1241'),
    ]

    operations = [
    ]
