# Generated by Django 3.2.14 on 2022-11-07 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_srupdt', '0007_auto_20221107_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiensi',
            name='forum_perencanaan_pernah_diusulkan',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='audiensi',
            name='kementerian_lembaga_daerah',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Kementrian/Lembaga/Daerah'),
        ),
        migrations.AlterField(
            model_name='audiensi',
            name='rc_ded',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='audiensi',
            name='rc_fs',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='audiensi',
            name='rc_lahan',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='audiensi',
            name='rc_pra_fs',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='penelaahanawal',
            name='ketersediaan_proyek_usulan',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='penelaahanawal',
            name='memenuhi_kelengkapan_minimum_rediness_criteria',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='penelaahanawal',
            name='terdapat_identifikasi_kewenangan_pusatdaerah_dari_usulan_proyek',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='penelaahanawal',
            name='terdapat_justifikasi_kebutuhan_usulan_proyek',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='penelaahanawal',
            name='terdapat_nomenklatur_usulan_yang_jelas',
            field=models.BooleanField(),
        ),
    ]
