# Generated by Django 3.2.14 on 2022-11-07 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_srupdt', '0009_auto_20221107_1254'),
    ]

    operations = [
        migrations.RenameField(
            model_name='klinikkonsultasi',
            old_name='nodin_laporan',
            new_name='tautan_nodin_laporan',
        ),
        migrations.RenameField(
            model_name='klinikkonsultasi',
            old_name='surat_jawaban',
            new_name='tautan_surat_jawaban',
        ),
        migrations.AddField(
            model_name='surat',
            name='tautan_surat_masuk',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
