# Generated by Django 3.2.14 on 2022-11-07 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_srupdt', '0010_auto_20221107_1254'),
    ]

    operations = [
    ]
