# Generated by Django 3.2.14 on 2022-11-08 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_srupdt', '0011_auto_20221107_1257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiensi',
            name='catatan_audiensi',
        ),
        migrations.RemoveField(
            model_name='audiensi',
            name='keterangan_tambahan',
        ),
        migrations.AddField(
            model_name='audiensi',
            name='rc_amdal',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='audiensi',
            name='tautan_rc',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='audiensi',
            name='tautan_risalah_audiensi',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='penelaahanawal',
            name='catatan_penelaahan_awal',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='audiensi',
            name='kewenangan',
            field=models.CharField(blank=True, choices=[('pusat', 'Pemerintah Pusat'), ('provinsi', 'Pemerintah Daerah Provinsi'), ('kabupaten/kota', 'Pemerintah Kabupaten/Kota'), ('swasta', 'Swasta')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='klinikkonsultasi',
            name='tautan_nodin_laporan',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='klinikkonsultasi',
            name='tautan_surat_jawaban',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='surat',
            name='provinsi',
            field=models.CharField(blank=True, choices=[('11', 'Aceh'), ('12', 'Sumatera Utara'), ('13', 'Sumatera Barat'), ('14', 'Riau'), ('15', 'Jambi'), ('16', 'Sumatera Selatan'), ('17', 'Bengkulu'), ('18', 'Lampung'), ('19', 'Kep. Bangka Belitung'), ('21', 'Kep. Riau'), ('31', 'DKI Jakarta'), ('32', 'Jawa Barat'), ('33', 'Jawa Tengah'), ('34', 'DI Yogyakarta'), ('35', 'Jawa Timur'), ('36', 'Banten'), ('51', 'Bali')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='surat',
            name='tanggal_surat',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='surat',
            name='tautan_surat_masuk',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
