# Generated by Django 3.2.14 on 2022-09-29 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('sppr', 'SPPR'), ('srupdt', 'SRUPDT')], max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('uploader', 'Uploader'), ('berita-acara', 'Berita Acara'), ('pengesahan-usulan', 'Pengesahan Usulan'), ('album-tematik', 'Album Tematik'), ('kajian-kewilayahan', 'Kajian Kewilayahan'), ('isu-strategis', 'Permasalahan Isu Strategis')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('developer', 'Developer'), ('director', 'Director'), ('secretary', 'Secretary'), ('coordinator', 'Coordinator'), ('pic', 'PIC')], max_length=15)),
                ('app_access', models.ManyToManyField(related_name='AppAccess', to='app_login.App', verbose_name='App(s) Access')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='app_access',
        ),
        migrations.AddField(
            model_name='user',
            name='login_status',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.DeleteModel(
            name='Apps',
        ),
        migrations.AddField(
            model_name='app',
            name='list_menu',
            field=models.ManyToManyField(related_name='Menu', to='app_login.Menu'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Role', to='app_login.role', verbose_name='Role'),
        ),
    ]
