# Generated by Django 3.2.14 on 2022-11-03 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_login', '0002_auto_20220929_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='name',
            field=models.CharField(choices=[('kajian-kewilayahan', 'Kajian Kewilayahan'), ('situs-rajawali', 'Situs Rajawali')], max_length=30),
        ),
    ]
