# Generated by Django 3.2.14 on 2022-11-03 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_login', '0003_alter_menu_name'),
    ]

    operations = [
    ]
