# Generated by Django 3.2.14 on 2022-11-03 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_login', '0004_auto_20221103_1321'),
    ]

    operations = [
    ]
